# Generated by Django 4.2.7 on 2023-11-03 20:27

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='datapromo',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Última Promoção'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='150 characters or fewer. Letters (uppercase and lowercase), digits, @, :, -, and _ only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Enter a valid username. This value may contain only letters (uppercase and lowercase), numbers, @, :, -, and _ characters.', regex='^[a-zA-Z0-9@_:.,-]+$')], verbose_name='usuário'),
        ),
    ]
