# Generated by Django 4.2.6 on 2023-11-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treinamento', models.CharField(choices=[('CFSm (Curso de Formação de Marinheiros)', 'CFSm (Curso de Formação de Marinheiros)'), ('Curso de Aperfeiçoamento de Marinheiros (CASm)', 'Curso de Aperfeiçoamento de Marinheiros (CASm)'), ('Curso de Formação de Cabos (CFC)', 'Curso de Formação de Cabos (CFC)')], max_length=50, null=True)),
                ('sala', models.CharField(choices=[('CI', 'CI'), ('Sala [1]', 'Sala [1]'), ('Sala [2]', 'Sala [2]')], default='CI', max_length=50, null=True)),
                ('data1', models.DateTimeField(null=True, verbose_name='Início')),
                ('aprovados', models.TextField(max_length=50, null=True)),
                ('reprovados', models.TextField(max_length=50, null=True)),
                ('data2', models.DateTimeField(null=True, verbose_name='Fim')),
                ('observações', models.TextField(max_length=50, null=True)),
                ('responsavel', models.ForeignKey(limit_choices_to={'groups__name': 'oficiais'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo treinamento')),
                ('treinador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_treinador', to=settings.AUTH_USER_MODEL, verbose_name='Treinador')),
            ],
        ),
    ]
