# Generated by Django 4.2.6 on 2023-11-01 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='data1',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='data2',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='responsavel',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'oficial'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo treinamento'),
        ),
    ]
