# Generated by Django 4.2.6 on 2023-11-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0002_alter_relatorios_data1_alter_relatorios_data2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='data1',
            field=models.CharField(max_length=50, null=True, verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='data2',
            field=models.CharField(max_length=50, null=True, verbose_name='Fim'),
        ),
    ]
