# Generated by Django 4.2.6 on 2023-11-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0003_alter_relatorios_data1_alter_relatorios_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='data_preenchimento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
