# Generated by Django 4.2.6 on 2023-11-01 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatorios', '0004_relatorios_data_preenchimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='treinador',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_treinador', to=settings.AUTH_USER_MODEL, verbose_name='Treinador'),
        ),
    ]
