# Generated by Django 4.2.6 on 2023-11-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0006_alter_relatorios_treinador'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='status',
            field=models.CharField(choices=[('Espera...', 'Espera...'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], max_length=50, null=True),
        ),
    ]
