# Generated by Django 4.2.6 on 2023-11-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0007_relatorios_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='status',
            field=models.CharField(blank=True, choices=[('Espera...', 'Espera...'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], max_length=50, null=True),
        ),
    ]
