# Generated by Django 4.2.7 on 2023-11-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0012_alter_relatorios_status_alter_relatorios_treinador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='data_preenchimento',
            field=models.DateTimeField(blank=True),
        ),
    ]
