# Generated by Django 4.2.7 on 2023-11-04 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0002_alter_treinamentos_texto1_alter_treinamentos_texto2_and_more'),
        ('relatorios', '0013_alter_relatorios_data_preenchimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorios',
            name='treinamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treinamento', to='treinamentos.treinamentos', verbose_name='Treinamento'),
        ),
    ]
