# Generated by Django 4.2.6 on 2023-10-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(blank=True, null=True, verbose_name='Título')),
                ('texto1', models.TextField(blank=True, null=True, verbose_name='Texto-1')),
            ],
        ),
    ]
