# Generated by Django 4.2.6 on 2023-11-02 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcoes', models.CharField(choices=[('Promoção', 'Promoção'), ('Rebaixamento', 'Rebaixamento'), ('Demissão', 'Demissão')], max_length=50, null=True)),
                ('data_preenchimento', models.DateTimeField(auto_now=True)),
                ('militar', models.TextField(max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Espera...', 'Espera...'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Espera...', max_length=50, null=True)),
                ('solicitante', models.ForeignKey(limit_choices_to={'groups__name': 'oficial'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerimento_solicitante', to=settings.AUTH_USER_MODEL, verbose_name='Treinador')),
            ],
        ),
    ]
