# Generated by Django 4.2.7 on 2023-11-03 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='data_preenchimento',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='solicitante',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'oficial'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requerimento_solicitante', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='requerimento',
            name='status',
            field=models.CharField(choices=[('Espera...', 'Espera...'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Espera...', max_length=50, null=True),
        ),
    ]
