# Generated by Django 4.2.7 on 2023-11-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_requerimento_data_preenchimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimento',
            name='opcoes',
            field=models.CharField(choices=[('Promoção', 'Promoção'), ('Rebaixamento', 'Rebaixamento'), ('Demissão', 'Demissão'), ('Reserva', 'Reserva')], max_length=50, null=True),
        ),
    ]
