# Generated by Django 4.2.6 on 2023-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(verbose_name='Título')),
                ('topico1', models.TextField(verbose_name='Tópico-1')),
                ('texto1', models.TextField(verbose_name='Texto-1')),
                ('topico2', models.TextField(verbose_name='Tópico-2')),
                ('texto2', models.TextField(verbose_name='Texto-2')),
                ('topico3', models.TextField(verbose_name='Tópico-3')),
                ('texto3', models.TextField(verbose_name='Texto-3')),
                ('topico4', models.TextField(verbose_name='Tópico-4')),
                ('texto4', models.TextField(verbose_name='Texto-4')),
                ('topico5', models.TextField(verbose_name='Tópico-5')),
                ('texto5', models.TextField(verbose_name='Texto-5')),
                ('topico6', models.TextField(verbose_name='Tópico-6')),
                ('texto6', models.TextField(verbose_name='Texto-6')),
                ('topico7', models.TextField(verbose_name='Tópico-7')),
                ('texto7', models.TextField(verbose_name='Texto-7')),
            ],
        ),
    ]
