# Generated by Django 4.2.6 on 2023-10-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamentos',
            name='texto1',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-1'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto2',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-2'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto3',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-3'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto4',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-4'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto5',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-5'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto6',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-6'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='texto7',
            field=models.TextField(blank=True, null=True, verbose_name='Texto-7'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='titulo',
            field=models.TextField(blank=True, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico1',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-1'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico2',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-2'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico3',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-3'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico4',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-4'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico5',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-5'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico6',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-6'),
        ),
        migrations.AlterField(
            model_name='treinamentos',
            name='topico7',
            field=models.TextField(blank=True, null=True, verbose_name='Tópico-7'),
        ),
    ]
